#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use Mojolicious::Commands;

# Application
$ENV{MOJO_APP} = 'test';

# Start commands
Mojolicious::Commands->start;
